# Докерфайл для дафни для работы сокетов
FROM python:3.11

WORKDIR /app

RUN pip install daphne==4.0.0

COPY requirements.txt .


RUN pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["daphne", "-b", "0.0.0.0", "--port", "8020", "Backend.asgi:application"]